In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
  np.arange(10.0)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(-5,6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [7]:
np.arange(4,11)

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(4,11,dtype="float")

array([ 4.,  5.,  6.,  7.,  8.,  9., 10.])

In [9]:
np.arange(4,11,dtype="complex")

array([ 4.+0.j,  5.+0.j,  6.+0.j,  7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(1,11,5)

array([1, 6])

In [15]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])