In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
a[3]

4

In [5]:
a[4]

5

In [9]:
a[3]+a[4]

9

In [7]:
a[-1]

5

In [10]:
a[0]

1

In [11]:
b = np.array([500,200,4,6,19,20,3000])
b

array([ 500,  200,    4,    6,   19,   20, 3000])

In [12]:
b[4]

19

In [13]:
b[-3]

19

In [14]:
a

array([1, 2, 3, 4, 5])

In [15]:
a[2] = 100


In [16]:
a

array([  1,   2, 100,   4,   5])