In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
b = np.array([[1,2,3],[4,5,6]])
b


array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.ndim

2

In [7]:
a.ndim

1

In [9]:
li = [[1,2,3],[4,5,6],[7,8,9]]
c = np.array(li)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
tu = ((1,2,3),(4,5,6),(7,8,9))
d = np.array(tu)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])