In [13]:
import numpy as np

In [14]:
arr = np.array(1)
arr

array(1)

In [15]:
arr = np.array(2)
arr

array(2)

In [16]:
arr.ndim

0

In [17]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
a.ndim

1

In [19]:
li=[1,2,3,4]
b = np.array(li)
b

array([1, 2, 3, 4])

In [20]:
tu = (1,2,3,4,5,6,7,8,9,10)
c = np.array(tu)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
d = np.array((1,2,3,4))
d

array([1, 2, 3, 4])