In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a[1][1]

4

In [5]:
a[2][0]

5

In [6]:
a[0][0]

1

In [8]:
a[0][1] = 500
a

array([[  1, 500],
       [  3,   4],
       [  5,   6]])

In [9]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
b[2][1]

8

In [11]:
a[-1][-2]

5