In [45]:
import numpy as np

In [46]:
a = np.array([3,4,2,6])
a

array([3, 4, 2, 6])

In [47]:
b = np.array([8,6,5,10])
b

array([ 8,  6,  5, 10])

In [48]:
np.concatenate((a,b))

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [49]:
c = np.concatenate((a,b))
c

array([ 3,  4,  2,  6,  8,  6,  5, 10])

In [50]:
a

array([3, 4, 2, 6])

In [51]:
np.append(a,100)

array([  3,   4,   2,   6, 100])

In [52]:
np.append(a,500)

array([  3,   4,   2,   6, 500])

In [53]:
a = np.append(a,500)
a

array([  3,   4,   2,   6, 500])

In [54]:
a = np.append(a,1000)
a

array([   3,    4,    2,    6,  500, 1000])

In [55]:
b = np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [56]:
np.append(b,[[10],[20]],axis=1)

array([[ 1,  2, 10],
       [ 3,  4, 20]])

In [57]:
b


array([[1, 2],
       [3, 4]])

In [58]:
b = np.append(b,[[10],[20]],axis=1)
b

array([[ 1,  2, 10],
       [ 3,  4, 20]])