In [1]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [5]:
b = np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [6]:
c = a.dot(b)
c

array([[37, 40],
       [85, 92]])

เกิดจาก [[1x11+2x13, 1x12+2x14],[3x11+4x13, 3x12+4x14]]