In [1]:
import numpy as np

In [3]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
b = a.flatten()
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
b

array([1, 2, 3, 4, 5, 6])

In [12]:
b[0]=5
b

array([5, 2, 3, 4, 5, 6])

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
c = a.ravel()
c

array([1, 2, 3, 4, 5, 6])

In [19]:
c[0]=5
c

array([5, 2, 3, 4, 5, 6])

In [20]:
a

array([[5, 2],
       [3, 4],
       [5, 6]])

flatten เปลี่ยนจากหลายมิติเป็นมิติเดียว แต่จะไม่เป็นข้อมูลภายในถ้าเกิดการเปลี่ยนแปลงค่าใน array ถ้าจะให้ข้อมูลเปลี่ยนแปลงตามด้วยต้องใช้ ravel