In [1]:
import numpy as np

In [4]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
index = np.array([1,5,7])
index

array([1, 5, 7])

In [6]:
x[index]

array([2, 6, 8])

In [11]:
index = np.array([2,4,6,8])
x[index]

array([3, 5, 7, 9])

In [12]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [14]:
x[[2,4,6,8]]

array([3, 5, 7, 9])

In [21]:
b[[0,2]]

array([[1, 2, 3],
       [7, 8, 9]])

In [22]:
b[[0,2],[2,0]]

array([3, 7])

In [23]:
b[[0,2],[2]]

array([3, 9])

In [26]:
b[[0,2],[1]]

array([2, 8])

In [28]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x[2]

3

In [30]:
x[[2,3,4]]

array([3, 4, 5])

In [31]:
y = np.array([2,3,4])
x[y]

array([3, 4, 5])

In [32]:
x[[0,1]]

array([1, 2])

In [33]:
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
m = x[[1,4,1,4,1,4,1,4]]
m

array([2, 5, 2, 5, 2, 5, 2, 5])

In [37]:
x = np.array([[1,-2,3],[4,-5,-9]])
x

array([[ 1, -2,  3],
       [ 4, -5, -9]])

In [38]:
x[x<0]

array([-2, -5, -9])

In [39]:
x[x>2]

array([3, 4])

In [40]:
x[x<0]

array([-2, -5, -9])

In [41]:
x[x<0]*-1

array([2, 5, 9])

In [42]:
x[x<0]

array([-2, -5, -9])

In [45]:
x[x<0]*2

array([ -4, -10, -18])

In [43]:
x[x<0]*-2

array([ 4, 10, 18])

In [44]:
x[x<0]**2

array([ 4, 25, 81])