In [1]:
import numpy as np

append เป็นการต่อท้ายแต่ insert คือการแทรกข้อมูลลงใน array

In [2]:
a = np.array([1,2,4,5,8])
a

array([1, 2, 4, 5, 8])

In [3]:
np.append(a,40)

array([ 1,  2,  4,  5,  8, 40])

In [4]:
a

array([1, 2, 4, 5, 8])

In [5]:
np.insert(a,1,100)

array([  1, 100,   2,   4,   5,   8])

In [7]:
a

array([1, 2, 4, 5, 8])

In [8]:
np.insert(a,(1,3),100)

array([  1, 100,   2,   4, 100,   5,   8])