In [61]:
import numpy as np

In [62]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [63]:
a+2

array([3, 4, 5, 6])

In [64]:
a+10

array([11, 12, 13, 14])

In [65]:
a-5

array([-4, -3, -2, -1])

In [66]:
a*2

array([2, 4, 6, 8])

In [67]:
a*5

array([ 5, 10, 15, 20])

In [68]:
a**2

array([ 1,  4,  9, 16])

In [69]:
a%2

array([1, 0, 1, 0], dtype=int32)

In [70]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [71]:
a

array([1, 2, 3, 4])

In [72]:
b = np.arange(1,5)
b

array([1, 2, 3, 4])

In [73]:
a+b

array([2, 4, 6, 8])

In [74]:
a.shape

(4,)

In [75]:
b.shape

(4,)

In [76]:
c = np.arange(1,10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a+c 

ValueError: operands could not be broadcast together with shapes (4,) (9,) 

error เพราะต้องให้ array มีขนาดเท่ากัน

In [ ]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y = np.array([[7,8,9],[10,11,12]])
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
x+y

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
x*y

array([[ 7, 16, 27],
       [40, 55, 72]])

In [ ]:
x**y

array([[          1,         256,       19683],
       [    1048576,    48828125, -2118184960]])

In [ ]:
x/y

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [ ]:
x%y

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
x+[2]

array([[3, 4, 5],
       [6, 7, 8]])

In [ ]:
z = np.array([1,2])
z.shape

(2,)

In [ ]:
x.shape

(2, 3)

In [ ]:
x+z

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

บวกกันไม่ได้  มี 2 สาเหตุ คือ ขนาดของ array ต่างกัน / มิติต่างกัน


In [ ]:
z = np.array([1,2,3])
z.shape

(3,)

In [ ]:
x+z