In [1]:
import numpy as np

In [3]:
np.full(5,10)

array([10, 10, 10, 10, 10])

In [4]:
np.full(10,7)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

In [5]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [6]:
np.full([4,5],7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [7]:
np.full([4,5],3.5)

array([[3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5],
       [3.5, 3.5, 3.5, 3.5, 3.5]])