In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.ndim

1

In [6]:
b.ndim

2

In [7]:
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('int32')

In [10]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="complex")
b

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [11]:
b.dtype

dtype('complex128')

In [13]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b.dtype

dtype('int32')

In [14]:
a.shape

(5,)

In [15]:
b.shape

(3, 3)

In [18]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b.shape

(4, 3)

In [19]:
a.size

5

In [20]:
b.size

12

In [21]:
b.dtype

dtype('int32')

In [22]:
b.itemsize

4

In [23]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype="complex")
b.dtype


dtype('complex128')

In [25]:
b.itemsize

16