In [17]:
import numpy as np

In [18]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b = a.reshape((2,5))
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
a , b

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]))

In [23]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a.resize((2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])