In [1]:
import numpy as np

In [3]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[2]

3

In [5]:
a[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
a[7:]

array([ 8,  9, 10])

In [8]:
a[:5]

array([1, 2, 3, 4, 5])

In [9]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [11]:
b = np.array([20,10,30,50,40])
b[1:]

array([10, 30, 50, 40])

In [12]:
b[3:]

array([50, 40])

In [13]:
b[:3]

array([20, 10, 30])

In [14]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
a[3:7]

array([4, 5, 6, 7])

In [17]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
a[2:9:2]

array([3, 5, 7, 9])

In [21]:
b

array([20, 10, 30, 50, 40])

In [22]:
b[1:4]

array([10, 30, 50])

In [23]:
b[1:4:2]

array([10, 50])

In [25]:
c = np.array([10,30,40,50,60,70,75,90])
c

array([10, 30, 40, 50, 60, 70, 75, 90])

In [26]:
c[:]

array([10, 30, 40, 50, 60, 70, 75, 90])

In [27]:
c[::2]

array([10, 40, 60, 75])

In [28]:
c[::3]

array([10, 50, 75])