In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
x[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
x[1:,1:]

array([[5, 6],
       [8, 9]])

In [5]:
x[2:,2:]

array([[9]])

In [6]:
x[2:,1:]

array([[8, 9]])

In [7]:
x[:,2:]

array([[3],
       [6],
       [9]])

In [8]:
x[1:,:]

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
x[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
x[:2,2:]

array([[3],
       [6]])

In [11]:
x[1:2,1:2]

array([[5]])

In [13]:
x[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [14]:
x[1:2,:]

array([[4, 5, 6]])

In [15]:
x[::,::2]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [16]:
x[::,1:2]

array([[2],
       [5],
       [8]])