In [1]:
import numpy as np

In [2]:
a = np.array([10,5,4,6,99,100,50,30])
a

array([ 10,   5,   4,   6,  99, 100,  50,  30])

In [3]:
a.sum()

304

In [4]:
a.prod()

640130816

prod คือผลคูณทุกตัว

In [5]:
a.mean()

38.0

In [7]:
a.max()

100

In [8]:
a.min()

4

In [9]:
a.argmax()

5

In [10]:
a.argmin()

2

argmax และ argmin คือตำแหน่งของ array ที่ max และ min

In [11]:
b = np.array([[10,20,30],[40,50,90],[80,100,5]])
b

array([[ 10,  20,  30],
       [ 40,  50,  90],
       [ 80, 100,   5]])

axis0 คือ แนวตั้ง
axis1 คือ แนวนอน

In [12]:
np.min(b,axis=1)

array([10, 40,  5])

In [13]:
np.min(b,axis=0)

array([10, 20,  5])

In [14]:
np.max(b,axis=1)

array([ 30,  90, 100])

In [15]:
np.max(b,axis=0)

array([ 80, 100,  90])