In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b = a.transpose()
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
a.shape

(2, 3)

In [8]:
b.shape

(3, 2)